#!/usr/bin/env bash
cd "${1:-.}/app/src/main/java/"
file="$(find * -type f | head -n1)"
dir="$(dirname "$file" | tr '/' '.')"
file="$(echo "$file" | sed -r 's/.java$//' | tr '/' '.')"
adb shell am start -n "${dir}/${file}"
