#!/usr/bin/env bash
cd 'src/'
file="$(find * -type f | head -n1)"
dir="$(dirname "$file")"
file="$(echo "$file" | sed -r 's/.java$//' | tr '/' '.')"
dir="$(echo "$dir" | tr '/' '.')"
adb shell am start -n "${dir}/${file}"
